name: check
on: push
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      - uses: actions/setup-node@v4
      # run – произвольная bash-команда      
      - run: make setup
      - run: make test
      - run: make lint